const INCREMENTAR = 'INCREMENTAR'
const DECREMENTAR ='DECREMENTAR'
const OBTENER_PERSONAJES ='OBTENER_PERSONAJES'
const EPISODIO = 'EPISODIO'

export {
    INCREMENTAR,
    DECREMENTAR,
    OBTENER_PERSONAJES,
    EPISODIO,

}